# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream_tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stream_tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10stream_tts.proto\x12\x10speechkit.tts.v3\"\xad\x01\n\x0e\x43ontainerAudio\x12Q\n\x14\x63ontainer_audio_type\x18\x01 \x01(\x0e\x32\x33.speechkit.tts.v3.ContainerAudio.ContainerAudioType\"H\n\x12\x43ontainerAudioType\x12$\n CONTAINER_AUDIO_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08OGG_OPUS\x10\x02\"O\n\x12\x41udioFormatOptions\x12\x39\n\x0f\x63ontainer_audio\x18\x02 \x01(\x0b\x32 .speechkit.tts.v3.ContainerAudio\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x7f\n\x10SynthesisOptions\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x01\x12?\n\x11output_audio_spec\x18\x07 \x01(\x0b\x32$.speechkit.tts.v3.AudioFormatOptions\"\x1e\n\x0eSynthesisInput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x15\n\x13\x46orceSynthesisEvent\"\xd7\x01\n\x16StreamSynthesisRequest\x12\x35\n\x07options\x18\x01 \x01(\x0b\x32\".speechkit.tts.v3.SynthesisOptionsH\x00\x12;\n\x0fsynthesis_input\x18\x02 \x01(\x0b\x32 .speechkit.tts.v3.SynthesisInputH\x00\x12@\n\x0f\x66orce_synthesis\x18\x03 \x01(\x0b\x32%.speechkit.tts.v3.ForceSynthesisEventH\x00\x42\x07\n\x05\x45vent\"L\n\x17StreamSynthesisResponse\x12\x31\n\x0b\x61udio_chunk\x18\x01 \x01(\x0b\x32\x1c.speechkit.tts.v3.AudioChunk2y\n\x0bSynthesizer\x12j\n\x0fStreamSynthesis\x12(.speechkit.tts.v3.StreamSynthesisRequest\x1a).speechkit.tts.v3.StreamSynthesisResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAINERAUDIO']._serialized_start=39
  _globals['_CONTAINERAUDIO']._serialized_end=212
  _globals['_CONTAINERAUDIO_CONTAINERAUDIOTYPE']._serialized_start=140
  _globals['_CONTAINERAUDIO_CONTAINERAUDIOTYPE']._serialized_end=212
  _globals['_AUDIOFORMATOPTIONS']._serialized_start=214
  _globals['_AUDIOFORMATOPTIONS']._serialized_end=293
  _globals['_AUDIOCHUNK']._serialized_start=295
  _globals['_AUDIOCHUNK']._serialized_end=321
  _globals['_SYNTHESISOPTIONS']._serialized_start=323
  _globals['_SYNTHESISOPTIONS']._serialized_end=450
  _globals['_SYNTHESISINPUT']._serialized_start=452
  _globals['_SYNTHESISINPUT']._serialized_end=482
  _globals['_FORCESYNTHESISEVENT']._serialized_start=484
  _globals['_FORCESYNTHESISEVENT']._serialized_end=505
  _globals['_STREAMSYNTHESISREQUEST']._serialized_start=508
  _globals['_STREAMSYNTHESISREQUEST']._serialized_end=723
  _globals['_STREAMSYNTHESISRESPONSE']._serialized_start=725
  _globals['_STREAMSYNTHESISRESPONSE']._serialized_end=801
  _globals['_SYNTHESIZER']._serialized_start=803
  _globals['_SYNTHESIZER']._serialized_end=924
# @@protoc_insertion_point(module_scope)
